framework:
  messenger:
    failure_transport: failed

    transports:
      async:
        dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
        options:
          delete_after_ack: true

      sync: 'sync://'
      failed: 'doctrine://default?queue_name=failed'

    routing:
      Ria\Bundle\PostBundle\Messenger\Message\PostCreated: sync
      Ria\Bundle\PostBundle\Messenger\Message\PostUpdated: sync
      Ria\Bundle\PostBundle\Messenger\Message\PostDeleted: sync
      Ria\Bundle\PostBundle\Messenger\Message\PostSaved: sync
      Ria\Bundle\PostBundle\Messenger\Message\PostDateChanged: sync
      Ria\Bundle\PostBundle\Messenger\Message\PostArchived: sync
      Ria\Bundle\PostBundle\Messenger\Message\PostCanceled: sync
