services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Ria\Bundle\AdminBundle\:
      resource: '../../'
      exclude:
          - '../src/DependencyInjection/'
          - '../src/Entity/'
          - '../src/Tests/'

  Ria\Bundle\AdminBundle\Controller\:
      resource: "../../Controller"
      tags: ['controller.service_arguments']

  admin_language.language_request_listener:
    class: Ria\Bundle\AdminBundle\EventListener\LanguageRequestListener
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
