_bazinga_jstranslation:
  resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

ria_web:
  resource: "@RiaWebBundle/Controller"
  type: annotation
  prefix:
    ge: '' # don't prefix URLs for az, the default locale
    en: '/en'
    ru: '/ru'