parameters:
  app.speech_upload_directory: '%kernel.project_dir%/uploads/speech'

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Ria\Bundle\PostBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Command/'
      - '../../Form/Type'
      - '../../Tests/'

  Ria\Bundle\PostBundle\Controller\:
    resource: "../../Controller"
    tags: [ 'controller.service_arguments' ]

  Ria\Bundle\PostBundle\Handler\:
    resource: "../../Handler"
    tags:
      - { name: tactician.handler, typehints: true }

  Ria\Bundle\PostBundle\Form\Type\:
    resource: "../../Form/Type"
    tags: [ 'form.type' ]

  # Pipes
  Ria\Bundle\PostBundle\Pipe\:
    resource: "../../Pipe"
    public: true

  speech.manipulator:
    class: Ria\Bundle\PostBundle\Service\Speech\SpeechManipulator
    arguments:
      $uploadDirectory: '%app.speech_upload_directory%'

  Ria\Bundle\PostBundle\Service\Speech\SpeechManipulatorInterface: '@speech.manipulator'