<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    League\Tactician\Bundle\TacticianBundle::class => ['all' => true],
    FOS\CKEditorBundle\FOSCKEditorBundle::class => ['all' => true],
    Ria\Bundle\CoreBundle\RiaCoreBundle::class => ['all' => true],
    Ria\Bundle\UserBundle\RiaUserBundle::class => ['all' => true],
    Ria\Bundle\PostBundle\RiaPostBundle::class => ['all' => true],
    Ria\Bundle\PersonBundle\RiaPersonBundle::class => ['all' => true],
    Ria\Bundle\AdminBundle\RiaAdminBundle::class => ['all' => true],
    Ria\Bundle\WebBundle\RiaWebBundle::class => ['all' => true],
    Ria\Bundle\ThemeBundle\RiaThemeBundle::class => ['all' => true],
    Ria\Bundle\PhotoBundle\RiaPhotoBundle::class => ['all' => true],
    Ria\Bundle\WeatherBundle\RiaWeatherBundle::class => ['all' => true],
    Ria\Bundle\CurrencyBundle\RiaCurrencyBundle::class => ['all' => true],
    Ria\Bundle\VoteBundle\RiaVoteBundle::class => ['all' => true],
    Ria\Bundle\YoutubeBundle\RiaYoutubeBundle::class => ['all' => true],
    Ria\Bundle\ConfigBundle\RiaConfigBundle::class => ['all' => true],
    Ria\Bundle\StatisticBundle\RiaStatisticBundle::class => ['all' => true],
    Doctrine\Bundle\FixturesBundle\DoctrineFixturesBundle::class => ['dev' => true, 'test' => true],
    SymfonyBundles\RedisBundle\SymfonyBundlesRedisBundle::class => ['all' => true],
    Ria\Bundle\DataGridBundle\DataGridBundle::class => ['all' => true],
    Yectep\PhpSpreadsheetBundle\PhpSpreadsheetBundle::class => ['all' => true],
    Bazinga\Bundle\JsTranslationBundle\BazingaJsTranslationBundle::class => ['all' => true],
    Karser\Recaptcha3Bundle\KarserRecaptcha3Bundle::class => ['all' => true],
];
