services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  Ria\Bundle\ConfigBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
      - '../../Command/'
      - '../../Tests/'

  Ria\Bundle\ConfigBundle\Controller\:
    resource: "../../Controller"
    tags: [ 'controller.service_arguments' ]

  Ria\Bundle\ConfigBundle\Handler\:
    resource: "../../Handler"
    tags:
      - { name: tactician.handler, typehints: true }